#spring.profiles.active=prod
##spring.profiles.active=dev
## auto update the DB Schema
#spring.jpa.hibernate.ddl-auto=update
#
##Debugging
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
##debugging
#spring.jpa.properties.hibernate.format_sql=true


#newchpt
# General Configuration
spring.application.name=toolswap
spring.profiles.active=${APP_PROFILE:dev}

# Database Structure (Variables filled at runtime)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security/JWT (Variable filled at runtime)
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration.ms=${JWT_EXPIRATION:86400000}

# Cloudinary (Variable filled at runtime)
cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true